# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  KUBE_DOMAIN: api.flat.kubernetes.tobiasz.memleak.pl

stages:
  - build
  - review
  - deploy
  - cleanup

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-dev:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: deploy
  script:
    - kubectl get cs
    - command scripts/deploy
  environment:
    name: dev
    url: http://dev.api.flat.kubernetes.tobiasz.memleak.pl
  only:
    - master


review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: review
  script:
    - command scripts/deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - command scripts/destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

