# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

#services:
#  - docker:dind

stages:
  - build
  - deploy

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-dev:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: deploy
  script:
    - kubectl get cs
    - kubectl apply -f configs/k8s-service.yml
  environment:
    name: dev
    url: http://dev.api.flat.kubernetes.tobiasz.memleak.pl
  when: manual
