image: docker:latest

variables:
  KUBE_DOMAIN: api.flat.kubernetes.tobiasz.memleak.pl

stages:
  - build-test
  - test
  - build
  - review
  - deploy
  - cleanup

build-test:
  stage: build-test
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-ci-tests" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-ci-tests"
  except:
    - master

test:
  image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-ci-tests"
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: flat_test
    MYSQL_ROOT_PASSWORD: super_tajne_haslo
  script:
    - bash scripts/create_ci_test_config
    - cd app && python3 manage.py test --noinput

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-dev:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: deploy
  script:
    - command scripts/deploy
  environment:
    name: dev
    url: http://dev.$KUBE_DOMAIN
  only:
    - master


review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: review
  script:
    - command scripts/deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: cleanup
  script:
    - command scripts/destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

