FROM python:3-alpine

RUN apk add --no-cache gcc musl-dev g++

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt/flat/app

ADD requirements.txt /opt/flat
# Skip PostgreSQL client dependency (use builtin SQLite driver)
RUN sed -i '/psycopg/d' /opt/flat/requirements.txt
RUN pip install -r /opt/flat/requirements.txt

ADD app /opt/flat/app

VOLUME /opt/flat/app
WORKDIR /opt/flat/app
EXPOSE 8000

RUN python manage.py migrate

CMD python manage.py runserver 0.0.0.0:8000
