FROM python:3-alpine

RUN apk add --no-cache gcc musl-dev g++ postgresql-dev

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt/flat
WORKDIR /opt/flat
ADD requirements.txt /opt/flat
RUN pip install -r requirements.txt
ADD app /opt/flat

