version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - .:/opt/flat
    ports:
      - "8000:8000"
    depends_on:
      - migration

  migration:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - .:/opt/flat
    command: python manage.py migrate
