version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./app:/opt/flat/app
    ports:
      - "8000:8000"
    depends_on:
      - migration

  migration:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./app:/opt/flat/app
    command: python manage.py migrate
