# Generated by Django 2.0.1 on 2018-06-29 23:47

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion

from charges.models import Profile, Flat


def create_default_flat(apps, schema_editor):
    Flat.objects.create(name='Default')


def create_profiles_for_users(apps, schema_editor):
    flat = Flat.objects.first()
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, flat=flat)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charges', '0002_change_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('join_token', models.CharField(max_length=32, db_index=True)),
            ],
        ),
        migrations.RunPython(create_default_flat),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charges.Flat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_for_users),
    ]
