# Generated by Django 2.0.1 on 2019-02-17 13:25

from django.db import migrations, models
import django.db.models.deletion

CATEGORIES = [
    'Groceries',
    'Restaurants',
    'Transport',
    'Shopping',
    'Utility',
    'Entertainment',
    'Services',
    'Other',
]


def initiate_categories(apps, schema_editor):
    Category = apps.get_model('charges', 'Category')
    for cat in CATEGORIES:
        Category(name=cat).save()


def remove_categories(apps, schema_editor):
    Category = apps.get_model('charges', 'Category')
    Category.objects.filter(name=CATEGORIES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('charges', '0003_create_room_and_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charges.Category'),
        ),
        migrations.RunPython(initiate_categories, remove_categories),
    ]
