kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev
  labels:
    app: flat-dev
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flat-dev
      tier: api
  template:
    metadata:
      labels:
        app: flat-dev
        tier: api
    spec:
      containers:
      - name: api
        image: registry.gitlab.memleak.pl:443/flat/flat-api:feature-dockerize
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: dev
  labels:
    app: flat-dev
    tier: api
spec:
  selector:
    app: flat-dev
    tier: api
  ports:
  - name: web
    port: 80
    targetPort: web

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev
  labels:
    app: flat-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "dev.api.flat.kubernetes.tobiasz.memleak.pl"
    http:
      paths:
      - path: /
        backend:
          serviceName: dev
          servicePort: 80

