#!/usr/bin/env bash

cat > "app/flat_api_django/local.py"  <<EOF
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k#xfum2s88z=a++od3x66c5gzk&c3qqd-_g1%&vuxeyh&vxi-n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

GCM_KEY = 'gcm_key'


CORS_ORIGIN_ALLOW_ALL = True

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '$MYSQL_DATABASE',
        'USER': 'root',
        'PASSWORD': '$MYSQL_ROOT_PASSWORD',
        'HOST': 'mysql',
        'PORT': '3306',
    }
}

FCM_SERVER_KEY = ''
EOF