#!/usr/bin/env bash

set -e 

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DEPLOY_ROOT_DIR/common.bash"

ensure_environment_url
ensure_deploy_variables

CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_URL}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/http:\/\//}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/https:\/\//}"

echo "Creating namespace $KUBE_NAMESPACE"

cat <<EOF | kubectl apply -f -
kind: Namespace
apiVersion: v1
metadata:
  name: $KUBE_NAMESPACE
EOF

kubectl create secret -n $KUBE_NAMESPACE \
  docker-registry gitlab-registry \
  --docker-server="$CI_REGISTRY" \
  --docker-username="$CI_REGISTRY_USER" \
  --docker-password="$CI_REGISTRY_PASSWORD" \
  --docker-email="$GITLAB_USER_EMAIL" \
  -o yaml --dry-run | kubectl replace -n $KUBE_NAMESPACE --force -f -

track="${1-stable}"
name="$CI_ENVIRONMENT_SLUG"

if [[ "$track" != "stable" ]]; then
  name="$name-$track"
fi

replicas="1"

env_track="${track^^}"
env_slug="${CI_ENVIRONMENT_SLUG//-/_}"
env_slug="${env_slug^^}"

echo "Configuring database..."
mysql_name="${CI_ENVIRONMENT_SLUG}-mysql"
mysql_app="${CI_ENVIRONMENT_SLUG}-mysql"

MYSQL_USER="${MYSQL_USER:-user}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-password}"
MYSQL_DATABASE="${MYSQL_DATABASE:-$env_slug}"

cat <<EOF | kubectl apply -n $KUBE_NAMESPACE --force -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $mysql_name
  namespace: $KUBE_NAMESPACE
  labels:
    app: $mysql_app
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $mysql_app
      tier: database
  template:
    metadata:
      labels:
        name: $mysql_name
        app: $mysql_app
        tier: database
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: app
        image: mariadb:10
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          value: "$MYSQL_USER"
        - name: MYSQL_PASSWORD
          value: "$MYSQL_PASSWORD"
        - name: MYSQL_DATABASE
          value: "$MYSQL_DATABASE"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        ports:
        - name: mysql
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: $mysql_name
  namespace: $KUBE_NAMESPACE
  labels:
    app: $mysql_app
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: $mysql_app
    tier: database
EOF

echo "Waiting for deployment..."
kubectl rollout status -n "$KUBE_NAMESPACE" -w "deployment/$mysql_name"


echo "Migrating database..."
cat <<EOF | kubectl apply -n $KUBE_NAMESPACE --force -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: $name-migrate-db
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    track: "$track"
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_BUILD_ID"
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        name: $name-migrate-db
        app: $CI_ENVIRONMENT_SLUG
        track: "$track"
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG
        imagePullPolicy: Always
        command: ["bash", "scripts/docker_entry_migration", "debug"]
        env:
        - name: CI_BUILD_ID
          value: "$CI_BUILD_ID"
        - name: RAILS_SECRET_KEY
          value: "k#xfum2s88z=a++od3x66c5gzk&c3qqd-_g1%&vuxeyh&vxi-n"
        - name: RAILS_DEBUG 
          value: "True"
        - name: RAILS_ALLOWED_HOST
          value: "*"
        - name: RAILS_GCM_KEY
          value: "gcm_key"
        - name: RAILS_CORS_ALLOW_ALL
          value: "True"
        - name: RAILS_CORS_WHITELIST
          value: ""
        - name: RAILS_DB_NAME
          value: "$MYSQL_DATABASE"
        - name: RAILS_DB_USER 
          value: "$MYSQL_USER"
        - name: RAILS_DB_PASS
          value: "$MYSQL_PASSWORD"
        - name: RAILS_DB_HOST
          value: "$mysql_name"
        - name: RAILS_DB_PORT
          value: "3306"
EOF

echo "Wait for migration"
until kubectl -n "$KUBE_NAMESPACE" get jobs $name-migrate-db -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep True ; do echo -n '.'; sleep 1 ; done

echo "Deleting job"
kubectl -n "$KUBE_NAMESPACE" delete jobs/$name-migrate-db

echo "Deploying $CI_ENVIRONMENT_SLUG (track: $track, replicas: $replicas) with $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG..."
cat <<EOF | kubectl apply -n $KUBE_NAMESPACE --force -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $name
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    track: "$track"
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_BUILD_ID"
    tier: api
spec:
  replicas: $replicas
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      tier: api
      track: "$track"
  template:
    metadata:
      labels:
        name: $name
        app: $CI_ENVIRONMENT_SLUG
        track: "$track"
        tier: api
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG
        imagePullPolicy: Always
        env:
        - name: CI_BUILD_ID
          value: "$CI_BUILD_ID"
        - name: RAILS_SECRET_KEY
          value: "k#xfum2s88z=a++od3x66c5gzk&c3qqd-_g1%&vuxeyh&vxi-n"
        - name: RAILS_DEBUG 
          value: "True"
        - name: RAILS_ALLOWED_HOST
          value: "*"
        - name: RAILS_GCM_KEY
          value: "gcm_key"
        - name: RAILS_CORS_ALLOW_ALL
          value: "True"
        - name: RAILS_CORS_WHITELIST
          value: ""
        - name: RAILS_DB_NAME
          value: "$MYSQL_DATABASE"
        - name: RAILS_DB_USER 
          value: "$MYSQL_USER"
        - name: RAILS_DB_PASS
          value: "$MYSQL_PASSWORD"
        - name: RAILS_DB_HOST
          value: "$mysql_name"
        - name: RAILS_DB_PORT
          value: "3306"
        ports:
        - name: api
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_BUILD_ID"
spec:
  ports:
    - name: api
      port: 80
      targetPort: api
  selector:
    app: $CI_ENVIRONMENT_SLUG
    tier: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$CI_BUILD_ID"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $CI_ENVIRONMENT_HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: $CI_ENVIRONMENT_SLUG
          servicePort: 80
EOF

echo "Waiting for deployment..."
kubectl rollout status -n "$KUBE_NAMESPACE" -w "deployment/$name"

echo "Application is accessible at: ${CI_ENVIRONMENT_URL}"
echo ""
