#!/usr/bin/env bash

set -e 

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export SCRIPTS_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo "Docker entry script location $SCRIPTS_ROOT_DIR"

source "$SCRIPTS_ROOT_DIR/docker_entry_common.bash"

create_config

cd app
python manage.py migrate
(echo "from django.contrib.auth.models import User; User.objects.create_superuser('dummy', 'admin@example.com', 'dummy')" | python manage.py shell ) || true
